lr: 1e-5
init_epoch: 0
epochs: 50
test_epoch: 46
restore: false
gpu_id: 0
is_debug: no
feat_dim: 2883
name: "coarse_mvp2m"
save_path: "results"
# train
# train_file_path: "data/train_list.txt"
# train_data_path: '/datasets/p2mppdata/p2mppdata/train'
# train_image_path: '/datasets//ShapeNetRendering'

# # test
# test_file_path: "data/test_list.txt"
# test_data_path: '/datasets/p2mppdata/p2mppdata/test'
# test_image_path: '/datasets/ShapeNetRendering'

# # coarse result
# coarse_result_file_path: "data/train_list.txt"
# coarse_result_data_path: '/datasets/p2mppdata/p2mppdata/train'
# coarse_result_image_path: '/datasets/ShapeNetRendering'

# train_file_path: "data/train_list.txt"
# train_data_path: 'C:\\ORamaVR\\Datasets\\p2mppdata\\p2mppdata\\train'
# train_image_path: 'C:\\ORamaVR\\Datasets\\ShapeNetRendering'

# test_file_path: "data/test_list.txt"
# test_data_path: 'C:\\ORamaVR\\Datasets\\p2mppdata\\p2mppdata\\test'
# test_image_path: 'C:\ORamaVR\Datasets\\ShapeNetRendering'

# coarse_result_file_path: "data/train_list.txt"
# coarse_result_data_path: 'C:\\ORamaVR\\Datasets\\p2mppdata\\p2mppdata\\train'
# coarse_result_image_path: 'C:\\ORamaVR\\Datasets\\ShapeNetRendering'

train_file_path: "data/train_list.txt"
train_data_path: "UI/2023-11-06_101633_UTC/p2mppdata/train"
train_image_path: "LocalUpload/fcc97161e71a6afb42f16da05f735db3/ShapeNetRendering"

test_file_path: "data/test_list.txt"
test_data_path: "UI/2023-11-06_101633_UTC/p2mppdata/test/"
test_image_path: "LocalUpload/fcc97161e71a6afb42f16da05f735db3/ShapeNetRendering"

coarse_result_file_path: "data/train_list.txt"
coarse_result_data_path: 'C:\\ORamaVR\\Datasets\\p2mppdata\\p2mppdata\\train'
coarse_result_image_path: 'C:\\ORamaVR\\Datasets\\ShapeNetRendering'
