is_debug: no
# 3 + 3*(512+256+128+64)
feat_dim: 2883
# 3 + 3*(16+32+64)
stage2_feat_dim: 1347 #339 # Printed the shape of the blk1_proj_feat layer and 1347 popped, maybe 3 + 3*4*(16+32+64) = 1347
name: 'refine_p2mpp'
save_path: 'results'
# about cnn
load_cnn: no
pre_trained_cnn_path: 'results/coarse_mvp2m/models'
cnn_step: 46
# pre_trained_cnn_path: results/refine_p2mpp/models
# cnn_step: 10
# train
lr: 1e-5
epochs: 10
init_epoch: 47
gpu_id: 0
restore: false
train_file_path: 'data/train_list.txt'
train_data_path: 'C:\\ORamaVR\\Datasets\\p2mppdata\\p2mppdata\\train'
train_image_path: 'C:\\ORamaVR\\Datasets\\ShapeNetRendering'
train_mesh_root: 'results/coarse_mvp2m/coarse_intermediate/46'
# test
test_epoch: 10
test_file_path: 'data/test_list.txt'
test_data_path: 'C:\\ORamaVR\\Datasets\\p2mppdata\\p2mppdata\\test'
test_image_path: 'C:\ORamaVR\Datasets\\ShapeNetRendering'
test_mesh_root: 'results/coarse_mvp2m/predict/46'
